#+Title: Algoritmo para extracao de Dados de Relatórios pdf do S4

[[https://api.travis-ci.org/wagnermarques/datafromS4Reports.svg?branch=master]]


* Motivação
  O S4 é um software muito bom para área da saúde, mas nem sempre os
  relatórios são os que a gestão precisa a funcionalidade de extração de dados pra csv os
não está funcionando no momento.

* Alternativa
  A alternativa é gerar relatórios pdf e pegar os dados de lá.
  Pra isso, o que foi possível fazer, até o momento, é transformar o
  relatório em html, que é uma estrutura mais tranquila pra se
  trabalhar e depois extrair os dados em csv os quais podem ser
  abertos facilmente em excel ou importandos para banco de dados.
  
* Como isso acontece
  Tem um comando do linux que é o pdftohtml que faz a conversao do pdf
  pra html
  Pra disponibilizar esse comando tem que fazer a seguinte instalação.

  #+NAME: dnf install  poppler-utils
  #+BEGIN_SRC sh
  dnf install  poppler-utils
  #+END_SRC
  
  Dependendo da sua distribuição linux aí o camando vai mudar o
  comando, de acordo.

  Depois a conversão é desse jeito...
  #+NAME pdftohtml document-AnalitAlfabeGeriatria.pdf pdftohtmlOut.html
  #+BEGIN_SRC sh
  pdftohtml document-AnalitAlfabeGeriatria.pdf pdftohtmlOut.html
  #+END_SRC

  De poss2 do documento html dá pra fazer a extração...

* Estágio atual
  Por enquanto é possível apenas extrair dados do relatório de
  produção analítico alfabético.
  
  Os próximos passos podem ser já fazer a importação dos dados no
  banco de dados, mas tem alguma dificuldade com relação a integridade
  referencial dos dados e também com relação ao não repetição da
  inserção de dados por relatórios repetidos.


